#!/usr/bin/env bash
# Detects Mac LAN IP and writes it to app/src/config.ts

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/../app/src/config.ts"

# Try common macOS interfaces in order: Wi-Fi (en0), Ethernet (en1), others
IP=""
for iface in en0 en1 en2 en3; do
  CANDIDATE=$(ipconfig getifaddr "$iface" 2>/dev/null || true)
  if [[ -n "$CANDIDATE" ]]; then
    IP="$CANDIDATE"
    echo "Found IP $IP on $iface"
    break
  fi
done

if [[ -z "$IP" ]]; then
  echo "Error: could not detect a LAN IP. Check you are connected to Wi-Fi or Ethernet." >&2
  exit 1
fi

cat > "$CONFIG_FILE" <<EOF
// Auto-generated by scripts/set-ip.sh — do not commit (see config.example.ts)
export const SERVER_BASE_URL = 'http://${IP}:3000';
EOF

echo "Written to app/src/config.ts: http://${IP}:3000"
